AWSTemplateFormatVersion: '2010-09-09'
Description: 'Personal AI Chatbot - AI Stack (OpenSearch Serverless)'

Parameters:
  Environment:
    Type: String
  LambdaExecutionRoleArn:
    Type: String

Resources:
  VectorSearchCollection:
    Type: AWS::OpenSearchServerless::Collection
    Properties:
      Name: !Sub 'chatbot-vectors-${Environment}'
      Type: VECTORSEARCH
      Description: Vector database for RAG
      Tags:
        - Key: Environment
          Value: !Ref Environment

  VectorSearchAccessPolicy:
    Type: AWS::OpenSearchServerless::AccessPolicy
    Properties:
      Name: !Sub 'chatbot-vectors-policy-${Environment}'
      Type: data
      Policy: !Sub |
        [
          {
            "Rules": [
              {
                "ResourceType": "index",
                "Resource": ["index/chatbot-vectors-${Environment}/*"],
                "Permission": ["aoss:*"]
              }
            ],
            "Principal": ["${LambdaExecutionRoleArn}"]
          }
        ]

Outputs:
  VectorSearchEndpoint:
    Value: !GetAtt VectorSearchCollection.CollectionEndpoint
    Export:
      Name: !Sub '${AWS::StackName}-VectorEndpoint'

  VectorSearchDashboard:
    Value: !GetAtt VectorSearchCollection.DashboardEndpoint
