AWSTemplateFormatVersion: '2010-09-09'
Description: 'PAI Storage - DynamoDB and S3'

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    Description: Environment name (dev, staging, prod)

  KMSKeyArn:
    Type: String
    Description: KMS Key ARN for encryption

Resources:
  # DynamoDB Table for Short-term Memory (Conversations)
  ConversationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'pai-conversations-${EnvironmentName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: conversation_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: conversation_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref KMSKeyArn
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: PAI

  # DynamoDB Table for Memory Metadata
  MemoriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'pai-memories-${EnvironmentName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: memory_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: N
        - AttributeName: category
          AttributeType: S
      KeySchema:
        - AttributeName: memory_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: category-created_at-index
          KeySchema:
            - AttributeName: category
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref KMSKeyArn
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: PAI

  # S3 Bucket for Long-term Memory Storage
  LongTermMemoryBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'pai-long-term-memory-${AWS::AccountId}-${EnvironmentName}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !Ref KMSKeyArn
            BucketKeyEnabled: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: INTELLIGENT_TIERING
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 90
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: PAI

  # S3 Bucket Policy
  LongTermMemoryBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LongTermMemoryBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyUnencryptedObjectUploads
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Sub '${LongTermMemoryBucket.Arn}/*'
            Condition:
              StringNotEquals:
                's3:x-amz-server-side-encryption': 'aws:kms'

Outputs:
  ConversationsTableName:
    Description: DynamoDB Conversations Table Name
    Value: !Ref ConversationsTable
    Export:
      Name: !Sub '${AWS::StackName}-ConversationsTable'

  ConversationsTableArn:
    Description: DynamoDB Conversations Table ARN
    Value: !GetAtt ConversationsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ConversationsTableArn'

  MemoriesTableName:
    Description: DynamoDB Memories Table Name
    Value: !Ref MemoriesTable
    Export:
      Name: !Sub '${AWS::StackName}-MemoriesTable'

  MemoriesTableArn:
    Description: DynamoDB Memories Table ARN
    Value: !GetAtt MemoriesTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-MemoriesTableArn'

  LongTermMemoryBucketName:
    Description: S3 Long-term Memory Bucket Name
    Value: !Ref LongTermMemoryBucket
    Export:
      Name: !Sub '${AWS::StackName}-LongTermMemoryBucket'

  LongTermMemoryBucketArn:
    Description: S3 Long-term Memory Bucket ARN
    Value: !GetAtt LongTermMemoryBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LongTermMemoryBucketArn'
