AWSTemplateFormatVersion: '2010-09-09'
Description: 'PAI - Storage Resources (DynamoDB, S3)'

Parameters:
  Environment:
    Type: String
    Description: Environment name

Resources:
  # DynamoDB Table for Conversations
  ConversationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'PAI-Conversations-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: conversation_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: conversation_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: conversation_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: PAI

  # S3 Bucket for future RAG document storage
  DocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'pai-documents-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: PAI

Outputs:
  ConversationsTableName:
    Description: DynamoDB table name for conversations
    Value: !Ref ConversationsTable

  ConversationsTableArn:
    Description: DynamoDB table ARN
    Value: !GetAtt ConversationsTable.Arn

  DocumentsBucketName:
    Description: S3 bucket name for documents
    Value: !Ref DocumentsBucket

  DocumentsBucketArn:
    Description: S3 bucket ARN
    Value: !GetAtt DocumentsBucket.Arn
