name: Deploy Chatbot

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy infrastructure
        run: |
          chmod +x scripts/*.sh
          ./scripts/deploy.sh ${{ github.event.inputs.environment || 'dev' }}

      - name: Package and deploy Lambda
        run: |
          ./scripts/package-lambdas.sh ${{ github.event.inputs.environment || 'dev' }}

      - name: Run smoke tests
        run: |
          ./scripts/test.sh ${{ github.event.inputs.environment || 'dev' }}
